name: github-angular-actions

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Install, Lint and Build
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "avi-action-trigger" #Must be unique in Heroku
          heroku_email: "ravinashkvafs@gmail.com"
          healthcheck: "https://avi-action-trigger.herokuapp.com/health"
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Node Version Check
        run: node --version
      - name: NPM Version Check
        run: npm --version
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Build
        run: npm run build

  