name: github-angular-actions

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Install, Lint and Build
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Node Version Check
        run: node --version
      - name: NPM Version Check
        run: npm --version
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

  deploy:
    name: Deployment
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "heroku config name"
        run: git config user.name "Avinash Sharma"

      - name: "heroku config email"
        run: git config user.email "ravinashkvafs@gmail.com"

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "ec9ef8c5-6b51-4420-bfbc-8a938408cea2"
          heroku_app_name: "avi-action-trigger" #Must be unique in Heroku
          heroku_email: "ravinashkvafs@gmail.com"
          procfile: "web: npm start"

      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app email-service-web

      - name: "Releases the container"
        run: heroku container:release web --app email-service-web

  